CREATE TABLE Footfall(

  FootfallID SERIAL PRIMARY KEY,
  Timestamp TIMESTAMP NOT NULL,
  Location VARCHAR(255) NOT NULL,
  Duration INTERVAL,
  EntryPoint VARCHAR(255),
  ExitPoint VARCHAR(255),
  CustomerID INT,
  AgeGroup VARCHAR(50),
  Gender VARCHAR(50),
  GroupSize INT CHECK (GroupSize >0),
  WeatherCondition VARCHAR(255),
  DayOfTheWeek VARCHAR(50),
  Holiday BOOLEAN,
  SalesTransactionID INT,
  PromotionID INT,
  StaffOnDuty INT CHECK (StaffOnDuty >=0),
  QueueLength INT (QueueLength >=0) ,
  ProductInterest TEXT,
  CustomerFeedbackID INT,
  ExternalEvent TEXT,
  StoreCapacity INT (StoreCapacity >=0),
  SensorID INT,
  DwellTime INTERVAL,
  RepeatVisitor BOOLEAN,
  PurchaseMade BOOLEAN,
  StaffInteraction BOOLEAN,
  EngagementLevel INT,
  CustomerMood VARCHAR(255),
  TrafficSource VARCHAR(255)
);
